name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.8
  build_test: ^0.10.2
  built_value_generator: ^5.4.0
  build_web_compilers: ^0.4.0
  test: ^0.12.35
  pageloader:
     git: https://github.com/google/pageloader.git
